package it.units.expressionserver.domain.response;

/**
 * The Response interface outlines the specifications for various response types
 * generated by the server. Any class implementing this interface represent a
 * distinct type of server response.
 */
public interface Response {
    /**
     * Prints the response as a string.
     *
     * @return The string representation of the response.
     */
    String printResponse();
}
